name: Add checklist comment to draft PRs

on:
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'プルリクエスト番号'
        required: true
        type: number

jobs:
  add-comment:
    if: >
      (github.event_name == 'pull_request' && 
       github.event.pull_request.draft == true && 
       github.event.pull_request.base.ref == 'main') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Add checklist comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // プルリクエスト番号を取得（手動実行時は入力値、自動実行時はイベントから）
            const prNumber = github.context.eventName === 'workflow_dispatch' 
              ? github.context.payload.inputs.pr_number
              : context.payload.pull_request.number;
            const repo = context.repo;
            const body = "レビューの効率化および手戻り抑止のために、作成者は以下をセルフチェックしてください\n\n" +
              "### 概要に以下を記載していること\n" +
              "- [ ] 動作確認をどんなパターンで行ったのかが書かれているか\n" +
              "- [ ] UI のデザインを変更した場合はキャプチャ画像、UI 操作を変更した場合は GIF 動画を添付しているか\n\n" +
              "### 変更内容が以下を満たしていること\n" +
              "- [ ] 既存のコンポーネントを変更した場合、その変更によるデグレードがないことを確認したか\n" +
              "- [ ] 他の類似の実装箇所と一貫した実装方法になっているか(一貫性のある実装か AI で確認可能)\n" +
              "- [ ] バックエンドサービスのコードを追加・変更した時は、テストコードも作成したか\n" +
              "- [ ] テストコードに作成したテストケースをどの観点で作成したのか、その妥当性を説明できるか。異常系のテストケースを作成したか\n" +
              "- [ ] フロントで処理に失敗したときに、その失敗の結果をユーザに通知するような実装になっているか";

            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body,
            });
