# 特定ブランチへのプルリクエスト作成時に、レビューチェックリストを自動追加するワークフロー(Bチーム向け)
name: Auto add review checklist to PRs

# プルリクエストが作成されたときに実行（opened のみ）
on:
  pull_request:
    types: [opened]
    # 対象ブランチのみで起動
    branches:
      - main

jobs:
  add-comment:
    runs-on: ubuntu-latest
    # プルリクエストにコメントを投稿するための権限設定
    permissions:
      issues: write
      pull-requests: write
    steps:
      # GitHub Scriptを使ってプルリクエストにチェックリストコメントを追加
      - name: Add checklist comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // プルリクエストの情報を取得
            const prNumber = context.payload.pull_request.number;
            const repo = context.repo;

            // レビューチェックリストのテンプレート
            const body = "レビューの効率化および手戻り抑止のために、作成者は以下をセルフチェックしてください\n\n" +
              "### 概要に以下を記載していること\n" +
              "- [ ] 動作確認をどんなパターンで行ったのかが書かれているか\n" +
              "- [ ] UI のデザインを変更した場合はキャプチャ画像、UI 操作を変更した場合は GIF 動画を添付しているか\n\n" +
              "### 変更内容が以下を満たしていること\n" +
              "- [ ] 既存のコンポーネントを変更した場合、その変更によるデグレードがないことを確認したか\n" +
              "- [ ] 他の類似の実装箇所と一貫した実装方法になっているか(一貫性のある実装か AI で確認可能)\n" +
              "- [ ] バックエンドサービスのコードを追加・変更した時は、テストコードも作成したか\n" +
              "- [ ] テストコードに作成したテストケースをどの観点で作成したのか、その妥当性を説明できるか。異常系のテストケースを作成したか\n" +
              "- [ ] フロントで処理に失敗したときに、その失敗の結果をユーザに通知するような実装になっているか";

            // プルリクエストにコメントを投稿
            await github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: prNumber,
              body,
            });
